### ISSUE TITLE
which Firewall port to open?

### ISSUE THREAD

**Issue by magdesign** [liamcottle/reticulum-meshchat#15]
I am successfully using meshchat on alpine linux / postmarketos.

I am able to receive messages, but to send messages i need to disable my nft firefall otherwise nothing goes out. So i want to add an exception but i am failing.
do i have to enable tcp or udp, which port number?

**Comment by magdesign** [comment]
not quite sure about this, i am able to send messeges to other devices within the same network with firewall enabled.. so maybe my friends lxmf address only works when he is online. closing this for now but kindly asking:
do we have a working echo bot for testing this things?

**Comment by liamcottle** [comment]
Hey, this entirely depends on what interfaces you use, what ports those interfaces use and if your firewall restricts inbound and outbound traffic.

For example, if you have a single `TCPClientInterface` that connects to the testnet server, via port 4965, generally you wouldn't need to open any ports, as firewalls usually allow all outbound traffic. This interface is making an outbound connection to the external server, so you wouldn't need to open an inbound port. If your firewall is restrictive on outbound traffic, for example at some schools or workplaces, you may need to open the outbound port as well.

If you are running a `TCPServerInterface`, this allows other clients, such as MeshChat, Sideband etc, to connect to you instead. In this setup, you would either need to be on the same local network, or you would need to open an external port and forward it to the port you configured for the interface.

As far as I know, if you only have the single interface enabled, and you are able to receive messages, then you should also be able to send messages, since your interface is connected. Something else is likely stopping the sending from happening, and based on your other issue #16 I would say the outdated python dependencies was the issue :)

> so maybe my friends lxmf address only works when he is online

Correct, you can not send any packets or messages to addresses if they are not reachable. So if your friend turns off their device, the packets will fail to send. LXMF propagation nodes can help you with that. They can receive your message on their behalf, and your friend can sync messages down to their device when they're next online.

> do we have a working echo bot for testing this things?

There used to be an echo bot that would reply to every single message you sent, however I believe that one has gone offline and the current echo bot will respond to 1 or 2 messages before telling you it's on cool down.

I may setup another one without any restrictions as it's very useful for testing :)

**Comment by magdesign** [comment]
Thank you so much for this detailed clarification, i hope this helps others too.
So i can go on in using/testing reticulum and understanding how to configure it (linux mobile).
